<a href="https://colab.research.google.com/github/EarvinColumna/Linear-Algebra-58020/blob/main/Final_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Final Exam

In [5]:
import numpy as np
from numpy.linalg import eig

####Problem 1. Student A, Student B, and Student C have a total of Php 89 cash in their banks. Student A has 6 less than Student C. Student B has 3 times what Student C has. How much does each student have? (30 points)

In [17]:
c = 19

a = (c-6)
b = (c*3)
c = c

print("Student A has: ",a)
print("Student B has: ",b)
print("Student C has: ",c)

Student A has:  13
Student B has:  57
Student C has:  19


####Problem 2. Solve each system: (30 points)

3x - y + z = 5

9x - 3y +3z = 15

-12x +4y -4z = -20 

In [18]:
A = np.array([[3,-1,1], [9,-3,3], [-12,4,-4]])
print("Matrix A:\n", A)
inv_A = np.linalg.pinv(A)
print("\nInverse of Matrix A:\n", inv_A)
B = np.array([[5],[10],[-20]])
print("\nMatrix A:\n", A)
X = np.dot(inv_A, B)
print("\nDot:\n", X)
C = np.dot(A, X)
print("\nChecking:\n", C)


Matrix A:
 [[  3  -1   1]
 [  9  -3   3]
 [-12   4  -4]]

Inverse of Matrix A:
 [[ 0.01048951  0.03146853 -0.04195804]
 [-0.0034965  -0.01048951  0.01398601]
 [ 0.0034965   0.01048951 -0.01398601]]

Matrix A:
 [[  3  -1   1]
 [  9  -3   3]
 [-12   4  -4]]

Dot:
 [[ 1.20629371]
 [-0.4020979 ]
 [ 0.4020979 ]]

Checking:
 [[  4.42307692]
 [ 13.26923077]
 [-17.69230769]]


### = Problem # 2 has no solution. We cannot use the inverse.

####Problem 3. Consider the matrix, (40 points)

1. Find the eigenvalue/s
2. Find the eigenvectors

In [15]:
A = np.array ([[8,5,-6],[-12,-9,12],[-3,-3,5]]) #Initialization of the array
print(A)# Displays the array
print("")
b,c = np.linalg.eig(A) #Finding the eigenvalues and eigenvectors of the given array
print("The eigenvalue/s is/are:",b) #Displays the eigenvalue/s of the given array
print("The eigenvectors are:",c) #Displays the eigenvectors of the given array

[[  8   5  -6]
 [-12  -9  12]
 [ -3  -3   5]]

The eigenvalue/s is/are: [-1.  3.  2.]
The eigenvectors are: [[ 3.01511345e-01 -7.07106781e-01  7.07106781e-01]
 [-9.04534034e-01  7.07106781e-01  1.53837015e-15]
 [-3.01511345e-01 -2.26120075e-15  7.07106781e-01]]
