<a href="https://colab.research.google.com/github/EarvinColumna/Linear-Algebra-58020/blob/main/Matrix_Inverse_and_Transpose.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Python program to inverse


In [8]:
import numpy as ay

In [28]:
##Create a Python program that applies an inverse of 3x3 or 4x4 matrix
A = ay.array([[5,2,3],[4,5,6],[7,8,9]])
print(A)

[[5 2 3]
 [4 5 6]
 [7 8 9]]


In [29]:
X = ay.transpose(A)
print(X)

[[5 4 7]
 [2 5 8]
 [3 6 9]]


In [30]:
##Create a Python program that applies transpose on a 3x3 or 4x4 matrix
Y = ay.linalg.inv(A)
print(Y)

[[ 0.25       -0.5         0.25      ]
 [-0.5        -2.          1.5       ]
 [ 0.25        2.16666667 -1.41666667]]


In [31]:
Z = ay.dot(A,Y)
print(Z)

[[ 1.00000000e+00  8.88178420e-16 -6.66133815e-16]
 [ 2.22044605e-16  1.00000000e+00  4.44089210e-16]
 [ 1.11022302e-16  1.77635684e-15  1.00000000e+00]]
