<a href="https://colab.research.google.com/github/EarvinColumna/Linear-Algebra-58020/blob/main/Midterm_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

#####Question 1.  Create a Python code that displays a square matrix whose length is 5 (10 points)


In [3]:
x = np.eye(5) #Displays the square matrix whose length is 5.
print(x)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


#####Question 2. Create a Python code that displays a square matrix whose elements below the principal diagonal are zero (10 points)



In [12]:
x = np.array([[1,2,3,4],[0,5,6,7],[0,0,9,8],[0,0,0,7]])
print(x)

[[1 2 3 4]
 [0 5 6 7]
 [0 0 9 8]
 [0 0 0 7]]


#####Question 3. Create a Python code that displays a square matrix which is symmetrical (10 points)




In [13]:
y = np.array([[1,2,6],[2,8,4],[6,4,5]]) # Displays a symmetrical square matrix.
print(y)

[[1 2 6]
 [2 8 4]
 [6 4 5]]


#####Question 4. What is the inverse of matrix C? Show your solution by python coding. (20 points)



In [10]:
v = np.array([[1,2,3],[2,3,3],[3,4,-2]])
print(v)
print("")
f = np.linalg.inv(v) # Converts the array into its inverse
print(f)

[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]

[[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]]


#####Question 5. What is the determinant of the given matrix in Question 4? Show your solution by python coding. (20 points)



In [11]:
v = np.array([[1,2,3],[2,3,3],[3,4,-2]])
print(v)
print("")
print(np.linalg.det(v)) #Shows the determinant of the given matrix
print("")
print(round(np.linalg.det(v)))

[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]

5.000000000000001

5


#####Question 6. Find the roots of the linear equations by showing its python codes (30 points)

5X1 + 4X2 + X3 = 3.4

10X1 + 9X2 + 4X3 = 8.8

10X1 + 13X2 + 15X3 = 19.2

In [16]:
j = np.array([[5,4,1,3.4],[10,9,4,8.8],[10,13,15,19.2]])
print(j)
print("")
g = np.sqrt(j) #Finds the roots of the given matrix.
print(g)

[[ 5.   4.   1.   3.4]
 [10.   9.   4.   8.8]
 [10.  13.  15.  19.2]]

[[2.23606798 2.         1.         1.84390889]
 [3.16227766 3.         2.         2.96647939]
 [3.16227766 3.60555128 3.87298335 4.38178046]]
