<a href="https://colab.research.google.com/github/EarvinColumna/Linear-Algebra-58020/blob/main/Practical_Lab_Exam_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Practical Lab Exam 1

#Problem 1

In [1]:
import numpy as np

In [45]:
W = np.array([[1,-3,0],[2,-2,0],[3,1,0]])
print(W)
X = np.array([[3,2,1],[-1,2,3],[2,-1,1]])
print(X)
Y = np.array([[1,2,0],[0,-1,2],[0,0,0]])
print(Y)
Z = np.array ([[0,1],[2,3]])
print(Z)

[[ 1 -3  0]
 [ 2 -2  0]
 [ 3  1  0]]
[[ 3  2  1]
 [-1  2  3]
 [ 2 -1  1]]
[[ 1  2  0]
 [ 0 -1  2]
 [ 0  0  0]]
[[0 1]
 [2 3]]


In [41]:
#a. WY
output = np.dot(W,Y)
print(output)

[[ 1  5 -6]
 [ 2  6 -4]
 [ 3  5  2]]


In [12]:
#b. Z+Z
output = np.add(Z,Z)
print(output)

[[0 2]
 [4 6]]


In [14]:
#c. 3X
output = np.dot(3,X)
print(output)

[[ 9  6  3]
 [-3  6  9]
 [ 6 -3  3]]


#Problem 2


In [42]:
#a. The product (YW)2 is not defined = False
ans1=np.cross(W,Y)
ans2= 2*ans1
print(ans2)

[[ 0  0 10]
 [-8 -8 -4]
 [ 0  0  0]]


In [17]:
#b. WY – X = False
b1 = np.dot(W,Y)
b2 = np.subtract(b1,X)
print(b2)

[[-2  3 -7]
 [ 3  4 -7]
 [ 1  6  1]]


In [20]:
#c. YW – Z2 = True
c1 = np.dot(Y,W)
c2 = 2*Z
c1 = ([[5,-7],[4,4]])
c3 = np.subtract(c1,c2)
print(c3)


[[ 5 -9]
 [ 0 -2]]


#Statement C is the true statement.