<a href="https://colab.research.google.com/github/EarvinColumna/Linear-Algebra-58020/blob/main/Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Prelim Exam

In [1]:
import numpy as np

#Question 1

In [27]:
C = np.eye(4)
print(C)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


#Question 2


In [28]:
Ans = 2*C
print(Ans)

[[2. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 2.]]


#Question 3

In [30]:
A = np.array([2,7,4])
B = np.array([3,9,8])
X = np.cross(A,B)
print(X)

[20 -4 -3]
